### ISSUE TITLE
No support for google colab

### ISSUE THREAD

**Issue by shlomi-schwartz** [Technion-Kishony-lab/quibbler#553]
As far as I could test, I couldn't make quibbler work on Google colab

**Comment by TalIfargan** [comment]
I was able to make it work by replacing:

`%matplotlib tk`

with:

`%matplotlib widget
from google.colab import output
output.enable_custom_widget_manager()`

That's not a solution, just a workaround I am suggesting.

**Comment by TalIfargan** [comment]
I was able to make it work by replacing:

```
%matplotlib tk
```

with:

```
%matplotlib widget
from google.colab import output
output.enable_custom_widget_manager()
```

That's not a solution, just a workaround I am suggesting.

**Comment by shlomi-schwartz** [comment]
Strange ... I'm getting the following error:

-```
--------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-1-4fa4b34893d8>](https://localhost:8080/#) in <module>
----> 1 get_ipython().run_line_magic('matplotlib', 'widget')
      2 from google.colab import output
      3 output.enable_custom_widget_manager()

13 frames
<decorator-gen-101> in matplotlib(self, line)

/usr/lib/python3.8/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

ModuleNotFoundError: No module named 'ipympl'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

**Comment by shlomi-schwartz** [comment]
So, I managed to get it going with the following settings:
```
!pip install ipympl
!pip install pyquibbler

%matplotlib widget
from google.colab import output
output.enable_custom_widget_manager()

import matplotlib.pyplot as plt

# matplotlib.use('TKAgg')
from pyquibbler import iquib
from pyquibbler import iquib, initialize_quibbler
initialize_quibbler()

y = iquib(0.5)
plt.plot([0,1],[0,1])
plt.plot(y,y,marker='o')
plt.title(y)
plt.show()
```

However it is very sluggish and slow

**Comment by TalIfargan** [comment]
It makes sense, Colab has a known issue for not supporting interactive Matplotlib figures [https://github.com/googlecolab/colabtools/issues/86](https://github.com/googlecolab/colabtools/issues/86). When Quibbler will support plotly we will also get `iplot()` which allows interactive plotly figures in Colab.

**Comment by rkishony** [comment]
Just pushed an update. It now allows running Quibbler in colab, including graphics, interactive quib viewing and quiby ipywidgets.

A demo colab notebook, based on @TalIfargan suggestion, is provided here:
https://colab.research.google.com/drive/1kZ3m8DdImiS0FJv8_VOZO8VuQdPkCBg8#scrollTo=q5rb_ooPWaVl

We note though that:
**QUIBBLER IS NOT WELL-SUITED TO WORK WITH COLAB.**
With the above settings, interactive graphics will work, but will be extremely slow. 
We strongly recommend working with *Quibbler* within a local environment. 

Commit: 792d9f985dc40096ad31003e0683b02d86401b3a
