### ISSUE TITLE
Cannot initialize quibbler. 

### ISSUE THREAD

**Issue by DyangLi** [Technion-Kishony-lab/quibbler#560]
Cannot initiate quibbler with `initialize_quibbler`, got error from `FileNotFoundError: Can't identify the notebook path. Can't identify the notebook path."` from `ipynbname.path()`. 

Package version in Python listed from:
[pkg.txt](https://github.com/Technion-Kishony-lab/quibbler/files/10262396/pkg.txt)

**Comment by rkishony** [comment]
I presume you are on Jupyter lab?
if so, pls try saving the notebook before running the script

**Comment by DyangLi** [comment]
Thanks! I tried on both jupyter notebook and jupyter lab and neither would work for me. I also tried saving the notebook before running without success.

**Comment by rkishony** [comment]
can you pls send the entire exception traceback?

**Comment by DyangLi** [comment]
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[1], line 11
      9 import pyquibbler as qb
     10 from pyquibbler import iquib
---> 11 qb.initialize_quibbler()

File ~/anaconda3/envs/quibbler/lib/python3.10/site-packages/pyquibbler/utilities/input_validation_utils.py:56, in validate_user_input.<locals>._decorator.<locals>._wrapper(*args, **kwargs)
     54     if not isinstance(arg_values.get(var_name), expected_types):
     55         raise InvalidArgumentTypeException(var_name=var_name, expected_type=expected_types)
---> 56 return func(*args, **kwargs)

File ~/anaconda3/envs/quibbler/lib/python3.10/site-packages/pyquibbler/function_overriding/override_all.py:91, in initialize_quibbler(draggable_plots, show_quibs_as_widgets)
     88 if IS_QUIBBLER_INITIATED:
     89     return
---> 91 within_jupyterlab = create_jupyter_project_if_in_jupyter_lab()
     93 func_definitions = create_definitions_for_python_functions()
     94 for func, func_definition in func_definitions.items():

File ~/anaconda3/envs/quibbler/lib/python3.10/site-packages/pyquibbler/project/jupyer_project/jupyter_project.py:260, in create_jupyter_project_if_in_jupyter_lab()
    258 project = JupyterProject.get_or_create()
    259 project.override_quib_persistence_functions()
--> 260 project.listen_for_events()
    261 project.get_save_within_notebook_state()
    262 project.set_undo_redo_buttons_enable_state()

File ~/anaconda3/envs/quibbler/lib/python3.10/site-packages/pyquibbler/project/jupyer_project/jupyter_project.py:203, in JupyterProject.listen_for_events(self)
    195 """
    196 Listen for all events from frontend- this will create a callback for any event coming from the frontend,
    197 and will run the relevant method for the event.
    198 It will then send BACK the response with the `request_id` specificed in the original event
    199 """
    201 from pyquibbler.optional_packages.get_IPython import Comm
--> 203 self._jupyter_notebook_path = os.environ.get("JUPYTER_NOTEBOOK", ipynbname.path())
    204 self._comm = Comm(target_name='pyquibbler')
    205 action_names_to_funcs = {
    206     "undo": self.undo,
    207     "redo": self.redo,
   (...)
    213     "cleanup": self._cleanup,
    214 }

File ~/anaconda3/envs/quibbler/lib/python3.10/site-packages/ipynbname/__init__.py:93, in path()
     91     root_dir = Path(srv.get('root_dir') or srv['notebook_dir'])
     92     return root_dir / path
---> 93 raise FileNotFoundError(FILE_ERROR.format('path'))

FileNotFoundError: Can't identify the notebook path.

**Comment by rkishony** [comment]
So it seems that `ipynbname` fails identifying the name of the Jupyter notebook. 
(see several related ipynbname issues: https://github.com/msm1089/ipynbname/issues)

I merged a patch that allows Quibbler to run even if ipynbname fails. 
In this case, saving quibs to notebook is disabled.  To still enable saving to notebook, Quibbler will further suggest setting the notebook file path manually using:

`qb.get_project().set_jupyter_notebook_path(...)`

Commit: cfd20edc0f0287a874ed7411d19f010c31e22ffd

**Comment by DyangLi** [comment]
Thanks, now I'm able to explore Quibbler!

**Comment by rkishony** [comment]
Happy quibbling
